name: Continuous integration
on: [push, pull_request]
env:
  # Bump this number to invalidate the Github-actions cache
  cache-invalidation-key: 0
  nix-config: |
    trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo=
    substituters = https://cache.nixos.org https://hydra.iohk.io https://iohk.cachix.org

jobs:
  cabal-test:
    name: cabal test
    env:
      NIXSHELL: nix-shell --pure
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: ${{ env.nix-config }}
    - name: Cache ormolu
      uses: actions/cache@v2
      with:
        path: |
          /nix/store/zq90gfpqp8gmvdz01ay1skma07bk0zpn-ormolu-exe-ormolu-0.4.0.0.drv
          /nix/store/r9dgn8gkps84axd4xw5qcgwygccx64xk-ormolu-exe-ormolu-0.4.0.0
        key: ormolu-${{ runner.os }}-${{ hashFiles('nix/sources.json') }}
    - name: Build Nix dependencies
      run: $NIXSHELL --run "echo '=== Nix dependencies installed ==='"
    - name: Cache Cabal dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: cabal-deps-${{ runner.os }}-${{ hashFiles('nix/sources.json') }}-v${{ env.cache-invalidation-key }}-${{ hashFiles('linear-base.cabal') }}-${{ github.sha }}
        restore-keys: cabal-deps-${{ runner.os }}-${{ hashFiles('nix/sources.json') }}-v${{ env.cache-invalidation-key }}-${{ hashFiles('linear-base.cabal') }}-
    - name: Update Cabal's database
      run: $NIXSHELL --run "cabal update"
    - name: Build Cabal's dependencies
      run:  $NIXSHELL --run "cabal build --enable-tests --enable-benchmarks --dependencies-only"
    - name: Build
      run: $NIXSHELL --run "cabal build"
    - name: Test
      run: $NIXSHELL --run "cabal test"
    - name: Haddock
      run: $NIXSHELL --run "cabal haddock"

  ormolu:
    name: check formatting with ormolu
    env:
      NIXSHELL: nix-shell --pure
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: ${{ env.nix-config }}
    - name: Cache ormolu
      uses: actions/cache@v2
      with:
        path: |
          /nix/store/zq90gfpqp8gmvdz01ay1skma07bk0zpn-ormolu-exe-ormolu-0.4.0.0.drv
          /nix/store/r9dgn8gkps84axd4xw5qcgwygccx64xk-ormolu-exe-ormolu-0.4.0.0
        key: ormolu-${{ runner.os }}-${{ hashFiles('nix/sources.json') }}
    - name: Build Nix dependencies
      run: $NIXSHELL --run "echo '=== Nix dependencies installed ==='"
    - name: check formatting
      run: $NIXSHELL --run 'ormolu -m check $(find . -type f -name "*.hs-boot" -o -name "*.hs")'

  stack-build:
    name: stack build
    env:
      NIXSHELL: nix-shell --pure
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: ${{ env.nix-config }}
    - name: Cache ormolu
      uses: actions/cache@v2
      with:
        path: |
          /nix/store/zq90gfpqp8gmvdz01ay1skma07bk0zpn-ormolu-exe-ormolu-0.4.0.0.drv
          /nix/store/r9dgn8gkps84axd4xw5qcgwygccx64xk-ormolu-exe-ormolu-0.4.0.0
        key: ormolu-${{ runner.os }}-${{ hashFiles('nix/sources.json') }}
    - name: Build Nix dependencies
      run: $NIXSHELL --run "echo '=== Nix dependencies installed ==='"
    - name: Cache Stack dependencies
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: stack-deps-${{ runner.os }}-${{ hashFiles('nix/sources.json') }}-v${{ env.cache-invalidation-key }}-${{ hashFiles('stack.yaml.lock', 'linear-base.cabal') }}-${{ github.sha }}
        restore-keys: stack-deps-${{ runner.os }}-${{ hashFiles('nix/sources.json') }}-v${{ env.cache-invalidation-key }}-${{ hashFiles('stack.yaml.lock', 'linear-base.cabal') }}-
    - name: Build
      run: $NIXSHELL --run "stack build --pedantic --test --bench --no-run-tests --no-run-benchmarks"
